services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: moment
    container_name: postgres
    volumes:
      - moment:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  db_test:
    image: postgres
    container_name: postgres-test
    environment:
      POSTGRES_USER: test_myuser
      POSTGRES_PASSWORD: test_mypassword
      POSTGRES_DB: test_moment
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:5432'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-moment-backend
    environment:
      PORT: ${PORT}
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    env_file: ".env.prod"

volumes:
  moment:
    driver: local
